/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.ConexionDB;
import Clases.cFechayHora;
import java.awt.Color;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author moise
 */
public class frmAgregarMedicamento extends javax.swing.JFrame {

    /**
     * Creates new form frmAgregarMedico
     */
    public frmAgregarMedicamento() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icono.png")).getImage());
        txtid.setText(String.valueOf(auto_increment()));
    }

    ConexionDB cc = new ConexionDB();
    cFechayHora fecha = new cFechayHora();

    public int auto_increment() {
        String sql_sel = "select max(id) from medicamentos";
        ResultSet result = null;
        cc.conectar();
        result = cc.seleccionar(sql_sel);
        int id_px = 0;
        try {
            while (result.next()) {
                id_px = result.getInt(1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "el error: " + e.toString());
            //System.out.println(e.toString());
        }
        cc.cerrar();
        return ((id_px) + 1);
    }

    public void limpiar() {
        txtid.setText(String.valueOf(auto_increment()));
        txtnom_com.setText("");
        txtlab.setText("");
        txtcompuesto.setText("");
        txtestante.setText("");
        txtexistencia.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        psalir = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pdatos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnom_com = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtlab = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtcompuesto = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtestante = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtexistencia = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jfelaboracion = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jfvencimiento = new com.toedter.calendar.JDateChooser();
        pguardar = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(133, 156, 206));

        psalir.setBackground(new java.awt.Color(133, 156, 206));
        psalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                psalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                psalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                psalirMouseExited(evt);
            }
        });
        psalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close_peq.png"))); // NOI18N
        psalir.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Registro de Medicamentos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 382, Short.MAX_VALUE)
                .addComponent(psalir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(psalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 30));

        jPanel3.setBackground(new java.awt.Color(247, 247, 247));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pdatos.setBackground(new java.awt.Color(247, 247, 247));
        pdatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Médico"));
        pdatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Codigo:");
        pdatos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 27, 74, 26));

        txtid.setEditable(false);
        txtid.setBackground(new java.awt.Color(247, 247, 247));
        txtid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pdatos.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 28, 120, 26));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nombre Comercial:");
        pdatos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 126, 27));

        txtnom_com.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pdatos.add(txtnom_com, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 220, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Laboratorio:");
        pdatos.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 90, 27));

        txtlab.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pdatos.add(txtlab, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 200, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Compuesto:");
        pdatos.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 100, 27));

        txtcompuesto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pdatos.add(txtcompuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 240, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("No. de Estante:");
        pdatos.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, 120, 27));

        txtestante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pdatos.add(txtestante, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 50, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Cantidad:");
        pdatos.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 70, 27));

        txtexistencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pdatos.add(txtexistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 60, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Fecha de Elaboracion:");
        pdatos.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 140, 27));

        jfelaboracion.setDateFormatString("dd-MM-yyyy");
        pdatos.add(jfelaboracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 180, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Fecha de Vencimeinto:");
        pdatos.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 150, 27));

        jfvencimiento.setDateFormatString("dd-MM-yyyy");
        pdatos.add(jfvencimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 180, 30));

        pguardar.setBackground(new java.awt.Color(247, 247, 247));
        pguardar.setToolTipText("Guardar Médico");
        pguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pguardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pguardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pguardarMouseExited(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar.png"))); // NOI18N
        jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pguardarLayout = new javax.swing.GroupLayout(pguardar);
        pguardar.setLayout(pguardarLayout);
        pguardarLayout.setHorizontalGroup(
            pguardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pguardarLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pguardarLayout.setVerticalGroup(
            pguardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pguardarLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pdatos.add(pguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 60, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("*");
        pdatos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, 10));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("*");
        pdatos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, 10));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("*");
        pdatos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, 10));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("*");
        pdatos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, -1, 10));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("*");
        pdatos.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, -1, 10));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("*");
        pdatos.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, 10));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("*");
        pdatos.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, 10));

        jPanel3.add(pdatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 24, 656, 251));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 680, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void psalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psalirMouseEntered
        // TODO add your handling code here:
        psalir.setBackground(Color.red);
    }//GEN-LAST:event_psalirMouseEntered

    private void psalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psalirMouseExited
        // TODO add your handling code here:
        psalir.setBackground(new Color(133, 156, 206));
    }//GEN-LAST:event_psalirMouseExited

    private void psalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psalirMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_psalirMouseClicked

    private void pguardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pguardarMouseEntered
        // TODO add your handling code here:
        pguardar.setBackground(new Color(51, 204, 51));
    }//GEN-LAST:event_pguardarMouseEntered

    private void pguardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pguardarMouseExited
        // TODO add your handling code here:
        pguardar.setBackground(new Color(247, 247, 247));
    }//GEN-LAST:event_pguardarMouseExited

    private void pguardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pguardarMouseClicked
        // TODO add your handling code here:
        Date fe = jfelaboracion.getDate();
        Date fv = jfvencimiento.getDate();
        if (txtnom_com.getText().isEmpty()
                || txtlab.getText().isEmpty()
                || txtcompuesto.getText().isEmpty()
                || txtestante.getText().isEmpty()
                || txtexistencia.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Faltan ingresaro datos, revisar los campos del nombre comercial, laboratorio, compuesto, estante y cantidad esten llenos.");
        }else if(fe == null){
            JOptionPane.showMessageDialog(this, "Falta ingresar la fecha de elaboración del medicamento.");
        }else if(fv == null){
            JOptionPane.showMessageDialog(this, "Falta ingresar la fecha de vencimiento del medicamento.");
        }else{
            String sql_insert = "insert into medicamentos (nombre_com, laboratorio, compuesto, estante, existencias, f_elaboracion, f_vencimiento) values (upper('" + txtnom_com.getText().toString() + "'),upper('" + txtlab.getText().toString() + "'),upper('" + txtcompuesto.getText().toString() + "')," + txtestante.getText() + "," + txtexistencia.getText() + ",'" + fecha.ffecha(jfelaboracion) + "','" + fecha.ffecha(jfvencimiento) + "')";
            cc.conectar();
            cc.insertar(sql_insert);
            cc.cerrar();
            limpiar();
            JOptionPane.showMessageDialog(null, "Se ha ingresado exitosamente el medicamento.");
        }

    }//GEN-LAST:event_pguardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAgregarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAgregarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAgregarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAgregarMedicamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAgregarMedicamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private com.toedter.calendar.JDateChooser jfelaboracion;
    private com.toedter.calendar.JDateChooser jfvencimiento;
    private javax.swing.JPanel pdatos;
    private javax.swing.JPanel pguardar;
    private javax.swing.JPanel psalir;
    private javax.swing.JTextField txtcompuesto;
    private javax.swing.JTextField txtestante;
    private javax.swing.JTextField txtexistencia;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtlab;
    private javax.swing.JTextField txtnom_com;
    // End of variables declaration//GEN-END:variables
}
