/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.ConexionDB;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author moise
 */
public class frmAgregarMedico extends javax.swing.JFrame {

    /**
     * Creates new form frmAgregarMedico
     */
    public frmAgregarMedico() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icono.png")).getImage());
        txtid.setText(String.valueOf(auto_increment()));
    }
    
    ConexionDB cc = new ConexionDB();
    
    public int auto_increment(){
        String sql_sel = "select max(ID_Medico) from Medicos";
        ResultSet result = null;
        cc.conectar();
        result = cc.seleccionar(sql_sel);
        int id_px=0;
        try {
            while (result.next()){
                id_px = result.getInt(1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "el error: "+e.toString());
            //System.out.println(e.toString());
        }
        cc.cerrar();
        return ((id_px)+1);
    }
    
    public void limpiar(){
        txtid.setText(String.valueOf(auto_increment()));
        txtdni1.setText("");
        txtnombre.setText("");
        txtdireccion.setText("");
        txtcelular.setText("");
        txtcorreo.setText("");
        txtespecialidad.setText("");
        txtcolegiacion.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        psalir = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pdatos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtdni1 = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtcelular = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtespecialidad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtcolegiacion = new javax.swing.JTextField();
        pguardar = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(133, 156, 206));

        psalir.setBackground(new java.awt.Color(133, 156, 206));
        psalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                psalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                psalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                psalirMouseExited(evt);
            }
        });
        psalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close_peq.png"))); // NOI18N
        psalir.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Registro de Médicos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 424, Short.MAX_VALUE)
                .addComponent(psalir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(psalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 30));

        jPanel3.setBackground(new java.awt.Color(247, 247, 247));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pdatos.setBackground(new java.awt.Color(247, 247, 247));
        pdatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Médico"));
        pdatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("N° Médico:");
        pdatos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 27, 74, 26));

        txtid.setEditable(false);
        txtid.setBackground(new java.awt.Color(247, 247, 247));
        txtid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pdatos.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 28, 120, 26));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("DNI:");
        pdatos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 60, 74, 26));

        try {
            txtdni1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtdni1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pdatos.add(txtdni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 62, 160, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nombre Completo:");
        pdatos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 97, 126, 27));

        txtnombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pdatos.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 97, 500, 25));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Dirección:");
        pdatos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 135, 70, 27));

        txtdireccion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pdatos.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 137, 550, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Celular:");
        pdatos.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 60, 27));

        try {
            txtcelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtcelular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcelularActionPerformed(evt);
            }
        });
        pdatos.add(txtcelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 160, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Correo:");
        pdatos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 60, 27));

        txtcorreo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pdatos.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 350, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Especialidad:");
        pdatos.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 90, 27));

        txtespecialidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pdatos.add(txtespecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 200, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("N:°. Colegiación");
        pdatos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 110, 27));

        txtcolegiacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pdatos.add(txtcolegiacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 220, -1));

        jPanel3.add(pdatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 24, 656, 251));

        pguardar.setBackground(new java.awt.Color(247, 247, 247));
        pguardar.setToolTipText("Guardar Médico");
        pguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pguardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pguardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pguardarMouseExited(evt);
            }
        });

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar.png"))); // NOI18N
        jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout pguardarLayout = new javax.swing.GroupLayout(pguardar);
        pguardar.setLayout(pguardarLayout);
        pguardarLayout.setHorizontalGroup(
            pguardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );
        pguardarLayout.setVerticalGroup(
            pguardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel3.add(pguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 60, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 680, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void psalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psalirMouseEntered
        // TODO add your handling code here:
        psalir.setBackground(Color.red);
    }//GEN-LAST:event_psalirMouseEntered

    private void psalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psalirMouseExited
        // TODO add your handling code here:
        psalir.setBackground(new Color (133,156,206));
    }//GEN-LAST:event_psalirMouseExited

    private void psalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psalirMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_psalirMouseClicked

    private void txtcelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcelularActionPerformed

    private void pguardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pguardarMouseEntered
        // TODO add your handling code here:
        pguardar.setBackground(new Color(51,204,51));
    }//GEN-LAST:event_pguardarMouseEntered

    private void pguardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pguardarMouseExited
        // TODO add your handling code here:
        pguardar.setBackground(new Color(247,247,247));
    }//GEN-LAST:event_pguardarMouseExited

    private void pguardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pguardarMouseClicked
        // TODO add your handling code here:
        if (txtdni1.getText().isEmpty() || txtnombre.getText().isEmpty() || txtdireccion.getText().isEmpty() || txtcelular.getText().isEmpty() 
                || txtcorreo.getText().isEmpty() || txtespecialidad.getText().isEmpty() || txtcolegiacion.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Faltan datos por ingresar, revisar que todos los campos se encuentren llenos en el formulario.");
        }
        else{
            String sql_insert="insert into Medicos (DNI, Nombre, Direccion, Celular, Correo, Especialidad, No_Colegiacion) values ('"+txtdni1.getText().toString()+"',upper('"+ txtnombre.getText().toString() +"'),upper('"+ txtdireccion.getText().toString() +"'), '"+ txtcelular.getText().toString() +"',lower('"+ txtcorreo.getText().toString() +"'),upper('"+ txtespecialidad.getText().toString() +"'),'"+ txtcolegiacion.getText().toString() +"')";
            cc.conectar();
            cc.insertar(sql_insert);
            cc.cerrar();
            limpiar();
            JOptionPane.showMessageDialog(null, "Se ha registrado el Médico con éxito.");
            this.dispose();
        }
        
    }//GEN-LAST:event_pguardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAgregarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAgregarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAgregarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAgregarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAgregarMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel pdatos;
    private javax.swing.JPanel pguardar;
    private javax.swing.JPanel psalir;
    private javax.swing.JFormattedTextField txtcelular;
    private javax.swing.JTextField txtcolegiacion;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JFormattedTextField txtdni1;
    private javax.swing.JTextField txtespecialidad;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
