/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.ConexionDB;
import static Formularios.frmCitas.txtidmed;
import static Formularios.frmCitas.txtidpx;
import static Formularios.frmConsultas.txtidcita;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author moise
 */
public class frmConfirmarCita extends javax.swing.JFrame {

    /**
     * Creates new form frmMedicamentos
     */
    public frmConfirmarCita() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    ConexionDB cc = new ConexionDB();
    
    public void ingresar_sql(){
        int idpaciente = Integer.parseInt(txtcidp.getText());
        int idMedico = Integer.parseInt(txtcidmed.getText());
        String fechacc = txtcfecha.getText();
        String hora = txtchora.getText();
        String motivo = txtmotivocita.getText();
        int idcm = 1;
        String estado = "PENDIENTE";
        String sql_insert = "insert into citas\n"
                + "(ID_PX,ID_Medico,fecha,hora,id_CentroMedico,motivo,estado) \n"
                + "values \n"
                + "("+idpaciente+","+idMedico+",'"+fechacc+"','"+hora+"',"+idcm+",upper('"+motivo+"'),'"+estado+"')";
        cc.conectar();
        cc.insertar(sql_insert);
        cc.cerrar();
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        psalir = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pprincipal = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtcid = new javax.swing.JTextField();
        txtcpaciente = new javax.swing.JTextField();
        txtcmedico = new javax.swing.JTextField();
        txtcespecialidad1 = new javax.swing.JTextField();
        txtccorreo = new javax.swing.JTextField();
        txtcfecha = new javax.swing.JTextField();
        txtchora = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtmotivocita = new javax.swing.JTextArea();
        pconfirmar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtcidp = new javax.swing.JTextField();
        txtcidmed = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(133, 156, 206));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        psalir.setBackground(new java.awt.Color(133, 156, 206));
        psalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                psalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                psalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                psalirMouseExited(evt);
            }
        });
        psalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close_peq.png"))); // NOI18N
        psalir.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        jPanel1.add(psalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 40, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Confirmación de Cita");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 470, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 30));

        pprincipal.setBackground(new java.awt.Color(247, 247, 247));
        pprincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("No. Cita");
        pprincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 39, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nombre del Paciente:");
        pprincipal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 73, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nombre del Médico:");
        pprincipal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Especialidad:");
        pprincipal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 144, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Fecha:");
        pprincipal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 207, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Hora:");
        pprincipal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        txtcid.setEditable(false);
        txtcid.setBackground(new java.awt.Color(0, 0, 0));
        txtcid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcid.setForeground(new java.awt.Color(255, 255, 255));
        pprincipal.add(txtcid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 36, 70, -1));

        txtcpaciente.setEditable(false);
        txtcpaciente.setBackground(new java.awt.Color(0, 0, 0));
        txtcpaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcpaciente.setForeground(new java.awt.Color(255, 255, 255));
        pprincipal.add(txtcpaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 70, 300, -1));

        txtcmedico.setEditable(false);
        txtcmedico.setBackground(new java.awt.Color(0, 0, 0));
        txtcmedico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcmedico.setForeground(new java.awt.Color(255, 255, 255));
        pprincipal.add(txtcmedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 104, 300, -1));

        txtcespecialidad1.setEditable(false);
        txtcespecialidad1.setBackground(new java.awt.Color(0, 0, 0));
        txtcespecialidad1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcespecialidad1.setForeground(new java.awt.Color(255, 255, 255));
        pprincipal.add(txtcespecialidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 141, 200, -1));

        txtccorreo.setEditable(false);
        txtccorreo.setBackground(new java.awt.Color(0, 0, 0));
        txtccorreo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtccorreo.setForeground(new java.awt.Color(255, 255, 255));
        pprincipal.add(txtccorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 174, 350, -1));

        txtcfecha.setEditable(false);
        txtcfecha.setBackground(new java.awt.Color(0, 0, 0));
        txtcfecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcfecha.setForeground(new java.awt.Color(255, 255, 255));
        pprincipal.add(txtcfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 207, 140, -1));

        txtchora.setEditable(false);
        txtchora.setBackground(new java.awt.Color(0, 0, 0));
        txtchora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtchora.setForeground(new java.awt.Color(255, 255, 255));
        pprincipal.add(txtchora, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 237, 140, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Correo Médico:");
        pprincipal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 177, 130, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Motivo de Cita");
        pprincipal.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 271, 130, -1));

        txtmotivocita.setEditable(false);
        txtmotivocita.setBackground(new java.awt.Color(0, 0, 0));
        txtmotivocita.setColumns(20);
        txtmotivocita.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtmotivocita.setForeground(new java.awt.Color(255, 255, 255));
        txtmotivocita.setRows(5);
        jScrollPane1.setViewportView(txtmotivocita);

        pprincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 294, 397, -1));

        pconfirmar.setBackground(new java.awt.Color(247, 247, 247));
        pconfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pconfirmarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pconfirmarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pconfirmarMouseExited(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cita.png"))); // NOI18N

        javax.swing.GroupLayout pconfirmarLayout = new javax.swing.GroupLayout(pconfirmar);
        pconfirmar.setLayout(pconfirmarLayout);
        pconfirmarLayout.setHorizontalGroup(
            pconfirmarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pconfirmarLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pconfirmarLayout.setVerticalGroup(
            pconfirmarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pconfirmarLayout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pprincipal.add(pconfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 297, -1, -1));
        pprincipal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 500, 10));

        txtcidp.setEditable(false);
        txtcidp.setBackground(new java.awt.Color(0, 0, 0));
        txtcidp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcidp.setForeground(new java.awt.Color(255, 255, 255));
        pprincipal.add(txtcidp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 38, -1));

        txtcidmed.setEditable(false);
        txtcidmed.setBackground(new java.awt.Color(0, 0, 0));
        txtcidmed.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcidmed.setForeground(new java.awt.Color(255, 255, 255));
        pprincipal.add(txtcidmed, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 107, 38, -1));

        getContentPane().add(pprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 520, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void psalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psalirMouseEntered
        // TODO add your handling code here:
        psalir.setBackground(Color.red);
    }//GEN-LAST:event_psalirMouseEntered

    private void psalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psalirMouseExited
        // TODO add your handling code here:
        psalir.setBackground(new Color(133,156,206));
    }//GEN-LAST:event_psalirMouseExited

    private void psalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psalirMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_psalirMouseClicked

    private void pconfirmarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pconfirmarMouseEntered
        // TODO add your handling code here:
        pconfirmar.setBackground(new Color(51,204,51));
    }//GEN-LAST:event_pconfirmarMouseEntered

    private void pconfirmarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pconfirmarMouseExited
        // TODO add your handling code here:
        pconfirmar.setBackground(new Color(247,247,247));
    }//GEN-LAST:event_pconfirmarMouseExited

    private void pconfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pconfirmarMouseClicked
        // TODO add your handling code here:
        ingresar_sql();
        JOptionPane.showMessageDialog(this, "Se ha Registrado y Notificado de Cita al Doctor con Éxito.");
        this.dispose();
        
    }//GEN-LAST:event_pconfirmarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmConfirmarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmConfirmarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmConfirmarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmConfirmarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmConfirmarCita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pconfirmar;
    private javax.swing.JPanel pprincipal;
    private javax.swing.JPanel psalir;
    public static javax.swing.JTextField txtccorreo;
    public static javax.swing.JTextField txtcespecialidad1;
    public static javax.swing.JTextField txtcfecha;
    public static javax.swing.JTextField txtchora;
    public static javax.swing.JTextField txtcid;
    public static javax.swing.JTextField txtcidmed;
    public static javax.swing.JTextField txtcidp;
    public static javax.swing.JTextField txtcmedico;
    public static javax.swing.JTextField txtcpaciente;
    public static javax.swing.JTextArea txtmotivocita;
    // End of variables declaration//GEN-END:variables
}
