/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.ConexionDB;
import static Formularios.frmConsultas.txtidcita;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author moise
 */
public class frmCancelarCita extends javax.swing.JFrame {

    /**
     * Creates new form frmMedicamentos
     */
    public frmCancelarCita() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icono.png")).getImage());
    }
    
    ConexionDB cc = new ConexionDB();
    frmCitas citas = new frmCitas();
    
    public void actualizarEstado(){
       int idcitac = Integer.valueOf(txtcid.getText());
       String motivoc = txtmotivoc.getText();
       String sql_act = "UPDATE citas SET estado='CANCELADO',motivo_c=upper('"+motivoc+"') WHERE id_citas="+idcitac;
       cc.conectar();
       cc.insertar(sql_act);
       cc.cerrar();
       JOptionPane.showMessageDialog(null, "Se ha Cancelado la Cita.");
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        psalir = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pprincipal = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtcid = new javax.swing.JTextField();
        txtcpaciente = new javax.swing.JTextField();
        txtcmedico = new javax.swing.JTextField();
        txtcespecialidad = new javax.swing.JTextField();
        txtcfecha = new javax.swing.JTextField();
        txtchora = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtmotivoc = new javax.swing.JTextArea();
        pcancelar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(133, 156, 206));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        psalir.setBackground(new java.awt.Color(133, 156, 206));
        psalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                psalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                psalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                psalirMouseExited(evt);
            }
        });
        psalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close_peq.png"))); // NOI18N
        psalir.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        jPanel1.add(psalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 40, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Cancelar Cita");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 470, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 30));

        pprincipal.setBackground(new java.awt.Color(247, 247, 247));
        pprincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("No. Cita");
        pprincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nombre del Paciente:");
        pprincipal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 59, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nombre del Médico:");
        pprincipal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 93, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Especialidad:");
        pprincipal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 127, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Fecha:");
        pprincipal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 161, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Hora:");
        pprincipal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 195, -1, -1));

        txtcid.setEditable(false);
        txtcid.setBackground(new java.awt.Color(0, 0, 0));
        txtcid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcid.setForeground(new java.awt.Color(255, 255, 255));
        pprincipal.add(txtcid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 22, 70, -1));

        txtcpaciente.setEditable(false);
        txtcpaciente.setBackground(new java.awt.Color(0, 0, 0));
        txtcpaciente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcpaciente.setForeground(new java.awt.Color(255, 255, 255));
        pprincipal.add(txtcpaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 56, 349, -1));

        txtcmedico.setEditable(false);
        txtcmedico.setBackground(new java.awt.Color(0, 0, 0));
        txtcmedico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcmedico.setForeground(new java.awt.Color(255, 255, 255));
        pprincipal.add(txtcmedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 90, 350, -1));

        txtcespecialidad.setEditable(false);
        txtcespecialidad.setBackground(new java.awt.Color(0, 0, 0));
        txtcespecialidad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcespecialidad.setForeground(new java.awt.Color(255, 255, 255));
        txtcespecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcespecialidadActionPerformed(evt);
            }
        });
        pprincipal.add(txtcespecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 124, 200, -1));

        txtcfecha.setEditable(false);
        txtcfecha.setBackground(new java.awt.Color(0, 0, 0));
        txtcfecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcfecha.setForeground(new java.awt.Color(255, 255, 255));
        pprincipal.add(txtcfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 158, 140, -1));

        txtchora.setEditable(false);
        txtchora.setBackground(new java.awt.Color(0, 0, 0));
        txtchora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtchora.setForeground(new java.awt.Color(255, 255, 255));
        pprincipal.add(txtchora, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 192, 140, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Motivo de Cancelación");
        pprincipal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 226, 144, -1));

        txtmotivoc.setColumns(20);
        txtmotivoc.setRows(5);
        jScrollPane1.setViewportView(txtmotivoc);

        pprincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 249, 397, -1));

        pcancelar.setBackground(new java.awt.Color(247, 247, 247));
        pcancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pcancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pcancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pcancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pcancelarMouseExited(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar_grande.png"))); // NOI18N

        javax.swing.GroupLayout pcancelarLayout = new javax.swing.GroupLayout(pcancelar);
        pcancelar.setLayout(pcancelarLayout);
        pcancelarLayout.setHorizontalGroup(
            pcancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pcancelarLayout.setVerticalGroup(
            pcancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        pprincipal.add(pcancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 269, 74, -1));

        getContentPane().add(pprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 520, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void psalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psalirMouseEntered
        // TODO add your handling code here:
        psalir.setBackground(Color.red);
    }//GEN-LAST:event_psalirMouseEntered

    private void psalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psalirMouseExited
        // TODO add your handling code here:
        psalir.setBackground(new Color(133,156,206));
    }//GEN-LAST:event_psalirMouseExited

    private void psalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psalirMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_psalirMouseClicked

    private void pcancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pcancelarMouseEntered
        // TODO add your handling code here:
        pcancelar.setBackground(Color.yellow);
    }//GEN-LAST:event_pcancelarMouseEntered

    private void pcancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pcancelarMouseExited
        // TODO add your handling code here:
        pcancelar.setBackground(new Color(247,247,247));
    }//GEN-LAST:event_pcancelarMouseExited

    private void txtcespecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcespecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcespecialidadActionPerformed

    private void pcancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pcancelarMouseClicked
        // TODO add your handling code here:
        actualizarEstado();
        this.dispose();
    }//GEN-LAST:event_pcancelarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCancelarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCancelarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCancelarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCancelarCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCancelarCita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pcancelar;
    private javax.swing.JPanel pprincipal;
    private javax.swing.JPanel psalir;
    public static javax.swing.JTextField txtcespecialidad;
    public static javax.swing.JTextField txtcfecha;
    public static javax.swing.JTextField txtchora;
    public static javax.swing.JTextField txtcid;
    public static javax.swing.JTextField txtcmedico;
    public static javax.swing.JTextField txtcpaciente;
    private javax.swing.JTextArea txtmotivoc;
    // End of variables declaration//GEN-END:variables
}
