/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.Color;
import java.sql.ResultSet;
import Clases.ConexionDB;

/**
 *
 * @author moise
 */
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class frmHPacientes extends javax.swing.JFrame {

    /**
     * Creates new form frmHPacientes
     */
    public frmHPacientes() {
        initComponents();
        this.setLocationRelativeTo(null);
        model = (DefaultTableModel) t_pacientes.getModel();
    }
    ConexionDB cc = new ConexionDB();
    DefaultTableModel model;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        psalir = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pprincipal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_pacientes = new javax.swing.JTable();
        pregreso = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtbuscar = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(133, 156, 206));

        psalir.setBackground(new java.awt.Color(133, 156, 206));
        psalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                psalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                psalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                psalirMouseExited(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close_peq.png"))); // NOI18N

        javax.swing.GroupLayout psalirLayout = new javax.swing.GroupLayout(psalir);
        psalir.setLayout(psalirLayout);
        psalirLayout.setHorizontalGroup(
            psalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );
        psalirLayout.setVerticalGroup(
            psalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 887, Short.MAX_VALUE)
                .addComponent(psalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(psalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 30));

        pprincipal.setBackground(new java.awt.Color(247, 247, 247));
        pprincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t_pacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° DNI", "Nombres", "Apellidos", "Celular", "Sexo", "T. Sangre", "Fecha Nacimiento"
            }
        ));
        jScrollPane1.setViewportView(t_pacientes);
        if (t_pacientes.getColumnModel().getColumnCount() > 0) {
            t_pacientes.getColumnModel().getColumn(0).setPreferredWidth(130);
            t_pacientes.getColumnModel().getColumn(0).setMaxWidth(130);
            t_pacientes.getColumnModel().getColumn(1).setPreferredWidth(180);
            t_pacientes.getColumnModel().getColumn(1).setMaxWidth(180);
            t_pacientes.getColumnModel().getColumn(2).setPreferredWidth(180);
            t_pacientes.getColumnModel().getColumn(2).setMaxWidth(180);
            t_pacientes.getColumnModel().getColumn(3).setPreferredWidth(100);
            t_pacientes.getColumnModel().getColumn(3).setMaxWidth(100);
            t_pacientes.getColumnModel().getColumn(4).setPreferredWidth(85);
            t_pacientes.getColumnModel().getColumn(4).setMaxWidth(85);
            t_pacientes.getColumnModel().getColumn(5).setPreferredWidth(100);
            t_pacientes.getColumnModel().getColumn(5).setMaxWidth(100);
            t_pacientes.getColumnModel().getColumn(6).setPreferredWidth(120);
            t_pacientes.getColumnModel().getColumn(6).setMaxWidth(120);
        }

        pprincipal.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 890, 340));

        pregreso.setBackground(new java.awt.Color(247, 247, 247));
        pregreso.setToolTipText("Regresar a Ventana Registro de Pacientes");
        pregreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pregresoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pregresoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pregresoMouseExited(evt);
            }
        });
        pregreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regreso.png"))); // NOI18N
        pregreso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        pprincipal.add(pregreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 40, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Ingrese el Nombre del Paciente a Buscar:");
        pprincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 240, 40));

        txtbuscar.setBackground(new java.awt.Color(247, 247, 247));
        txtbuscar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtbuscar.setBorder(null);
        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });
        pprincipal.add(txtbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 330, 20));
        pprincipal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 330, 10));

        getContentPane().add(pprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 920, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void psalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psalirMouseEntered
        // TODO add your handling code here:
        psalir.setBackground(Color.red);
    }//GEN-LAST:event_psalirMouseEntered

    private void psalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psalirMouseExited
        // TODO add your handling code here:
        psalir.setBackground(new Color(133,156,206));
    }//GEN-LAST:event_psalirMouseExited

    private void psalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psalirMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_psalirMouseClicked

    private void pregresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pregresoMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_pregresoMouseClicked

    private void pregresoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pregresoMouseEntered
        // TODO add your handling code here:
        pregreso.setBackground(new Color(243,106,54));
    }//GEN-LAST:event_pregresoMouseEntered

    private void pregresoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pregresoMouseExited
        // TODO add your handling code here:
        pregreso.setBackground(new Color(247,247,247));
    }//GEN-LAST:event_pregresoMouseExited

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String sql_sel="select  No_DNIPX, upper(Nombres_PX) as Nombres_PX, upper(Apellidos_PX) as Apellidos_PX, Celular_PX, upper(Sexo_PX) as Sexo_PX, upper(TSangre_PX) as TSangre_PX, FNacimiento_PX from Pacientes order by Nombres_PX";
        ResultSet result = null;
        cc.conectar();
        result = cc.seleccionar(sql_sel);
        try {
            while (result.next()){
                model.addRow(new Object[]{
                    result.getString("No_DNIPX"),
                    result.getString("Nombres_PX"),
                    result.getString("Apellidos_PX"),
                    result.getString("Celular_PX"),
                    result.getString("Sexo_PX"),
                    result.getString("TSangre_PX"),
                    result.getString("FNacimiento_PX")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "El Error es: "+e.toString());
        }
        cc.cerrar();
    }//GEN-LAST:event_formWindowOpened

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHPacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel pprincipal;
    private javax.swing.JPanel pregreso;
    private javax.swing.JPanel psalir;
    private javax.swing.JTable t_pacientes;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
