/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.Color;



/**
 *
 * @author elvi_
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState( MAXIMIZED_BOTH);
     
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn_salir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        p_px = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        p_cita = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        p_consulta = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        p_almacen = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        p_medicos = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        p_reportes = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(100, 100));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });

        btn_salir.setBackground(new java.awt.Color(255, 255, 255));
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close.png"))); // NOI18N
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(1064, Short.MAX_VALUE)
                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btn_salir)
                .addGap(0, 876, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        p_px.setBackground(new java.awt.Color(153, 153, 255));
        p_px.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                p_pxMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                p_pxMouseMoved(evt);
            }
        });
        p_px.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                p_pxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_pxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_pxMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                p_pxMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                p_pxMouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/patient.png"))); // NOI18N
        jLabel1.setText("Pacientes");

        javax.swing.GroupLayout p_pxLayout = new javax.swing.GroupLayout(p_px);
        p_px.setLayout(p_pxLayout);
        p_pxLayout.setHorizontalGroup(
            p_pxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_pxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        p_pxLayout.setVerticalGroup(
            p_pxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_pxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        p_cita.setBackground(new java.awt.Color(153, 153, 255));
        p_cita.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                p_citaMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                p_citaMouseMoved(evt);
            }
        });
        p_cita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_citaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_citaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                p_citaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                p_citaMouseReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cita.png"))); // NOI18N
        jLabel2.setText("Citas");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout p_citaLayout = new javax.swing.GroupLayout(p_cita);
        p_cita.setLayout(p_citaLayout);
        p_citaLayout.setHorizontalGroup(
            p_citaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_citaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        p_citaLayout.setVerticalGroup(
            p_citaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_citaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        p_consulta.setBackground(new java.awt.Color(153, 153, 255));
        p_consulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_consultaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_consultaMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/consulta.png"))); // NOI18N
        jLabel4.setText("Consulta");

        javax.swing.GroupLayout p_consultaLayout = new javax.swing.GroupLayout(p_consulta);
        p_consulta.setLayout(p_consultaLayout);
        p_consultaLayout.setHorizontalGroup(
            p_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_consultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        p_consultaLayout.setVerticalGroup(
            p_consultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_consultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        p_almacen.setBackground(new java.awt.Color(153, 153, 255));
        p_almacen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_almacenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_almacenMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/medicamento.png"))); // NOI18N
        jLabel5.setText("Almacen");

        javax.swing.GroupLayout p_almacenLayout = new javax.swing.GroupLayout(p_almacen);
        p_almacen.setLayout(p_almacenLayout);
        p_almacenLayout.setHorizontalGroup(
            p_almacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_almacenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        p_almacenLayout.setVerticalGroup(
            p_almacenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_almacenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        p_medicos.setBackground(new java.awt.Color(153, 153, 255));
        p_medicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_medicosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_medicosMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/medicos.png"))); // NOI18N
        jLabel6.setText("Medicos");

        javax.swing.GroupLayout p_medicosLayout = new javax.swing.GroupLayout(p_medicos);
        p_medicos.setLayout(p_medicosLayout);
        p_medicosLayout.setHorizontalGroup(
            p_medicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_medicosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        p_medicosLayout.setVerticalGroup(
            p_medicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_medicosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        p_reportes.setBackground(new java.awt.Color(153, 153, 255));
        p_reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                p_reportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                p_reportesMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reporte.png"))); // NOI18N
        jLabel3.setText("Reportes");

        javax.swing.GroupLayout p_reportesLayout = new javax.swing.GroupLayout(p_reportes);
        p_reportes.setLayout(p_reportesLayout);
        p_reportesLayout.setHorizontalGroup(
            p_reportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_reportesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        p_reportesLayout.setVerticalGroup(
            p_reportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_reportesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(p_px, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(p_consulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(p_cita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(p_almacen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(p_medicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(p_reportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(p_cita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_px, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_almacen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_medicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p_reportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(403, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 858, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void p_pxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_pxMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_pxMousePressed

    private void p_pxMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_pxMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_p_pxMouseReleased

    private void p_pxMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_pxMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_p_pxMouseMoved

    private void p_pxMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_pxMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_p_pxMouseDragged

    private void p_pxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_pxMouseEntered
        // TODO add your handling code here:
        p_px.setBackground(Color.WHITE);
    }//GEN-LAST:event_p_pxMouseEntered

    private void p_pxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_pxMouseExited
        // TODO add your handling code here:
        p_px.setBackground(new Color(153,153,255));
    }//GEN-LAST:event_p_pxMouseExited

    private void p_citaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_citaMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_p_citaMouseDragged

    private void p_citaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_citaMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_p_citaMouseMoved

    private void p_citaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_citaMouseEntered
        // TODO add your handling code here:
        p_cita.setBackground(Color.WHITE);
    }//GEN-LAST:event_p_citaMouseEntered

    private void p_citaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_citaMouseExited
        // TODO add your handling code here:
        p_cita.setBackground(new Color(153,153,255));
    }//GEN-LAST:event_p_citaMouseExited

    private void p_citaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_citaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_citaMousePressed

    private void p_citaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_citaMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_p_citaMouseReleased

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel2MouseEntered

    private void p_consultaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_consultaMouseExited
        // TODO add your handling code here:
        p_consulta.setBackground(new Color(153,153,255));
    }//GEN-LAST:event_p_consultaMouseExited

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseExited

    private void p_consultaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_consultaMouseEntered
        // TODO add your handling code here:
        p_consulta.setBackground(Color.WHITE);
    }//GEN-LAST:event_p_consultaMouseEntered

    private void p_almacenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_almacenMouseEntered
        // TODO add your handling code here:
        p_almacen.setBackground(Color.WHITE);
    }//GEN-LAST:event_p_almacenMouseEntered

    private void p_almacenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_almacenMouseExited
        // TODO add your handling code here:
        p_almacen.setBackground(new Color(153,153,255));
    }//GEN-LAST:event_p_almacenMouseExited

    private void p_medicosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_medicosMouseEntered
        // TODO add your handling code here:
        p_medicos.setBackground(Color.WHITE);
    }//GEN-LAST:event_p_medicosMouseEntered

    private void p_medicosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_medicosMouseExited
        // TODO add your handling code here:
        p_medicos.setBackground(new Color(153,153,255));
    }//GEN-LAST:event_p_medicosMouseExited

    private void p_reportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_reportesMouseEntered
        // TODO add your handling code here:
        p_reportes.setBackground(Color.WHITE);
    }//GEN-LAST:event_p_reportesMouseEntered

    private void p_reportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_reportesMouseExited
        // TODO add your handling code here:
        p_reportes.setBackground(new Color(153,153,255));
    }//GEN-LAST:event_p_reportesMouseExited

    private void p_pxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p_pxMouseClicked
        // TODO add your handling code here:
        frmPaciente abrir = new frmPaciente();
        abrir.setVisible(true);
    }//GEN-LAST:event_p_pxMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel p_almacen;
    private javax.swing.JPanel p_cita;
    private javax.swing.JPanel p_consulta;
    private javax.swing.JPanel p_medicos;
    private javax.swing.JPanel p_px;
    private javax.swing.JPanel p_reportes;
    // End of variables declaration//GEN-END:variables
}
