/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.Color;

/**
 *
 * @author moise
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        psalir = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblindouser = new javax.swing.JLabel();
        lblcargo = new javax.swing.JLabel();
        pcerrars = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        pprincipal = new javax.swing.JPanel();
        pcita = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ppaciente = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pmedico = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pconsulta = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        preportes = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pmedicamentos = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(133, 156, 206));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono.png"))); // NOI18N

        psalir.setBackground(new java.awt.Color(133, 156, 206));
        psalir.setToolTipText("Salir");
        psalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                psalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                psalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                psalirMouseExited(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close.png"))); // NOI18N

        javax.swing.GroupLayout psalirLayout = new javax.swing.GroupLayout(psalir);
        psalir.setLayout(psalirLayout);
        psalirLayout.setHorizontalGroup(
            psalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        psalirLayout.setVerticalGroup(
            psalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(psalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 400, Short.MAX_VALUE)
                .addComponent(psalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 500));

        jPanel2.setBackground(new java.awt.Color(245, 213, 199));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 57));

        lblindouser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblindouser.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(lblindouser, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 0, 355, 30));

        lblcargo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel2.add(lblcargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 36, 149, 21));

        pcerrars.setBackground(new java.awt.Color(245, 213, 199));
        pcerrars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pcerrarsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pcerrarsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pcerrarsMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cerrar-sesion.png"))); // NOI18N
        jLabel11.setText(" Cerrar Sesión");

        javax.swing.GroupLayout pcerrarsLayout = new javax.swing.GroupLayout(pcerrars);
        pcerrars.setLayout(pcerrarsLayout);
        pcerrarsLayout.setHorizontalGroup(
            pcerrarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        pcerrarsLayout.setVerticalGroup(
            pcerrarsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel2.add(pcerrars, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 170, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 800, 60));

        pprincipal.setBackground(new java.awt.Color(247, 247, 247));

        pcita.setBackground(new java.awt.Color(247, 247, 247));
        pcita.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pcita.setToolTipText("Cita");
        pcita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pcitaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pcitaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pcitaMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cita.png"))); // NOI18N
        jLabel5.setText(" Cita");

        javax.swing.GroupLayout pcitaLayout = new javax.swing.GroupLayout(pcita);
        pcita.setLayout(pcitaLayout);
        pcitaLayout.setHorizontalGroup(
            pcitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
        );
        pcitaLayout.setVerticalGroup(
            pcitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo_red.png"))); // NOI18N

        ppaciente.setBackground(new java.awt.Color(247, 247, 247));
        ppaciente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ppaciente.setToolTipText("Paciente");
        ppaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ppacienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ppacienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ppacienteMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/patient.png"))); // NOI18N
        jLabel6.setText(" Paciente");

        javax.swing.GroupLayout ppacienteLayout = new javax.swing.GroupLayout(ppaciente);
        ppaciente.setLayout(ppacienteLayout);
        ppacienteLayout.setHorizontalGroup(
            ppacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
        );
        ppacienteLayout.setVerticalGroup(
            ppacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pmedico.setBackground(new java.awt.Color(247, 247, 247));
        pmedico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pmedico.setToolTipText("Médico");
        pmedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pmedicoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pmedicoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pmedicoMouseExited(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/medicos.png"))); // NOI18N
        jLabel7.setText(" Médicos\n");

        javax.swing.GroupLayout pmedicoLayout = new javax.swing.GroupLayout(pmedico);
        pmedico.setLayout(pmedicoLayout);
        pmedicoLayout.setHorizontalGroup(
            pmedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
        );
        pmedicoLayout.setVerticalGroup(
            pmedicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
        );

        pconsulta.setBackground(new java.awt.Color(247, 247, 247));
        pconsulta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pconsulta.setToolTipText("Consulta/Facturación");
        pconsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pconsultaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pconsultaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pconsultaMouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/consulta.png"))); // NOI18N
        jLabel8.setText(" Consultas / Facturación");

        javax.swing.GroupLayout pconsultaLayout = new javax.swing.GroupLayout(pconsulta);
        pconsulta.setLayout(pconsultaLayout);
        pconsultaLayout.setHorizontalGroup(
            pconsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
        );
        pconsultaLayout.setVerticalGroup(
            pconsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
        );

        preportes.setBackground(new java.awt.Color(247, 247, 247));
        preportes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        preportes.setToolTipText("Reportes");
        preportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                preportesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                preportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                preportesMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reporte.png"))); // NOI18N
        jLabel9.setText(" Reportes");

        javax.swing.GroupLayout preportesLayout = new javax.swing.GroupLayout(preportes);
        preportes.setLayout(preportesLayout);
        preportesLayout.setHorizontalGroup(
            preportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
        );
        preportesLayout.setVerticalGroup(
            preportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pmedicamentos.setBackground(new java.awt.Color(247, 247, 247));
        pmedicamentos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pmedicamentos.setToolTipText("Almacén");
        pmedicamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pmedicamentosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pmedicamentosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pmedicamentosMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/medicamento.png"))); // NOI18N
        jLabel10.setText("Almacén");

        javax.swing.GroupLayout pmedicamentosLayout = new javax.swing.GroupLayout(pmedicamentos);
        pmedicamentos.setLayout(pmedicamentosLayout);
        pmedicamentosLayout.setHorizontalGroup(
            pmedicamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
        );
        pmedicamentosLayout.setVerticalGroup(
            pmedicamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pprincipalLayout = new javax.swing.GroupLayout(pprincipal);
        pprincipal.setLayout(pprincipalLayout);
        pprincipalLayout.setHorizontalGroup(
            pprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pprincipalLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(pprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pprincipalLayout.createSequentialGroup()
                        .addComponent(pcita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ppaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pmedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pprincipalLayout.createSequentialGroup()
                        .addComponent(pconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pmedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(preportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(91, 91, 91))
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pprincipalLayout.setVerticalGroup(
            pprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pprincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pcita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ppaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pmedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pconsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(preportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pmedicamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55))
        );

        getContentPane().add(pprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 800, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void psalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psalirMouseEntered
        // TODO add your handling code here:
        this.psalir.setBackground(Color.red);
    }//GEN-LAST:event_psalirMouseEntered

    private void psalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psalirMouseExited
        // TODO add your handling code here:
        this.psalir.setBackground(new Color(133,156,206));
    }//GEN-LAST:event_psalirMouseExited

    private void psalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psalirMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_psalirMouseClicked

    private void preportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preportesMouseExited
        // TODO add your handling code here:
        preportes.setBackground(new Color(247,247,247));
    }//GEN-LAST:event_preportesMouseExited

    private void preportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preportesMouseEntered
        // TODO add your handling code here:
        this.preportes.setBackground(new Color(133,156,206));
    }//GEN-LAST:event_preportesMouseEntered

    private void pconsultaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pconsultaMouseExited
        // TODO add your handling code here:
        pconsulta.setBackground(new Color(247,247,247));
    }//GEN-LAST:event_pconsultaMouseExited

    private void pconsultaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pconsultaMouseEntered
        // TODO add your handling code here:
        this.pconsulta.setBackground(new Color(133,156,206));
    }//GEN-LAST:event_pconsultaMouseEntered

    private void pmedicoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmedicoMouseExited
        // TODO add your handling code here:
        pmedico.setBackground(new Color(247,247,247));
    }//GEN-LAST:event_pmedicoMouseExited

    private void pmedicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmedicoMouseEntered
        // TODO add your handling code here:
        this.pmedico.setBackground(new Color(133,156,206));
    }//GEN-LAST:event_pmedicoMouseEntered

    private void ppacienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppacienteMouseExited
        // TODO add your handling code here:
        this.ppaciente.setBackground(new Color(247,247,247));
    }//GEN-LAST:event_ppacienteMouseExited

    private void ppacienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppacienteMouseEntered
        // TODO add your handling code here:
        this.ppaciente.setBackground(new Color(133,156,206));
    }//GEN-LAST:event_ppacienteMouseEntered

    private void ppacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ppacienteMouseClicked
        // TODO add your handling code here:
        frmPaciente abrir = new frmPaciente();
        abrir.setVisible(true);
    }//GEN-LAST:event_ppacienteMouseClicked

    private void pcitaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pcitaMouseExited
        // TODO add your handling code here:
        this.pcita.setBackground(new Color(247,247,247));
    }//GEN-LAST:event_pcitaMouseExited

    private void pcitaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pcitaMouseEntered
        // TODO add your handling code here:
        this.pcita.setBackground(new Color(133,156,206));
    }//GEN-LAST:event_pcitaMouseEntered

    private void pcitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pcitaMouseClicked
        // TODO add your handling code here:
        frmCitas abrir = new frmCitas();
        abrir.setVisible(true);
    }//GEN-LAST:event_pcitaMouseClicked

    private void pmedicamentosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmedicamentosMouseEntered
        // TODO add your handling code here:
        pmedicamentos.setBackground(new Color(133,156,206));
    }//GEN-LAST:event_pmedicamentosMouseEntered

    private void pmedicamentosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmedicamentosMouseExited
        // TODO add your handling code here:
        pmedicamentos.setBackground(new Color(247,247,247));
    }//GEN-LAST:event_pmedicamentosMouseExited

    private void pmedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmedicoMouseClicked
        // TODO add your handling code here:
        frmMedicos abrir = new frmMedicos();
        abrir.setVisible(true);
    }//GEN-LAST:event_pmedicoMouseClicked

    private void pmedicamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmedicamentosMouseClicked
        // TODO add your handling code here:
        frmMedicamentos abrir = new frmMedicamentos();
        abrir.setVisible(true);
    }//GEN-LAST:event_pmedicamentosMouseClicked

    private void preportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preportesMouseClicked
        // TODO add your handling code here:
        frmReportes abrir = new frmReportes();
        abrir.setVisible(true);
    }//GEN-LAST:event_preportesMouseClicked

    private void pconsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pconsultaMouseClicked
        // TODO add your handling code here:
        frmConsultas abrir = new frmConsultas();
        abrir.setVisible(true);
    }//GEN-LAST:event_pconsultaMouseClicked

    private void pcerrarsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pcerrarsMouseEntered
        // TODO add your handling code here:
        pcerrars.setBackground(new Color(133,156,206));
    }//GEN-LAST:event_pcerrarsMouseEntered

    private void pcerrarsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pcerrarsMouseExited
        // TODO add your handling code here:
        pcerrars.setBackground(new Color(245,213,199));
    }//GEN-LAST:event_pcerrarsMouseExited

    private void pcerrarsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pcerrarsMouseClicked
        // TODO add your handling code here:
        frmLogin abrir = new frmLogin();
        abrir.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pcerrarsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel lblcargo;
    public static javax.swing.JLabel lblindouser;
    private javax.swing.JPanel pcerrars;
    private javax.swing.JPanel pcita;
    private javax.swing.JPanel pconsulta;
    private javax.swing.JPanel pmedicamentos;
    private javax.swing.JPanel pmedico;
    private javax.swing.JPanel ppaciente;
    private javax.swing.JPanel pprincipal;
    private javax.swing.JPanel preportes;
    private javax.swing.JPanel psalir;
    // End of variables declaration//GEN-END:variables
}
