/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.IconoForm;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author moise
 */
public class frmReportes extends javax.swing.JFrame {

    /**
     * Creates new form frmMedicamentos
     */
    public frmReportes() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource(IconoForm.url())).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        psalir = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pprincipal = new javax.swing.JPanel();
        btnregresar = new javax.swing.JButton();
        btnreporteconsultaespecialidades = new javax.swing.JButton();
        btndemandacuposcentro = new javax.swing.JButton();
        btnreporteconsumomedicamentos = new javax.swing.JButton();
        btnreporteconsultascanceladas = new javax.swing.JButton();
        btnreimprimir = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(133, 156, 206));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        psalir.setBackground(new java.awt.Color(133, 156, 206));
        psalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                psalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                psalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                psalirMouseExited(evt);
            }
        });
        psalir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close_peq.png"))); // NOI18N
        psalir.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        jPanel1.add(psalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 40, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Reportes");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 30));

        pprincipal.setBackground(new java.awt.Color(247, 247, 247));

        btnregresar.setBackground(new java.awt.Color(247, 247, 247));
        btnregresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnregresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/regreso.png"))); // NOI18N
        btnregresar.setToolTipText("regresar al menú");
        btnregresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnregresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnregresarMouseExited(evt);
            }
        });
        btnregresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregresarActionPerformed(evt);
            }
        });

        btnreporteconsultaespecialidades.setBackground(new java.awt.Color(247, 247, 247));
        btnreporteconsultaespecialidades.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnreporteconsultaespecialidades.setText("Reporte de Consultas por Especialidades");
        btnreporteconsultaespecialidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnreporteconsultaespecialidadesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnreporteconsultaespecialidadesMouseExited(evt);
            }
        });
        btnreporteconsultaespecialidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreporteconsultaespecialidadesActionPerformed(evt);
            }
        });

        btndemandacuposcentro.setBackground(new java.awt.Color(247, 247, 247));
        btndemandacuposcentro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btndemandacuposcentro.setText("Demanda de Cupos en Centros Médicos");
        btndemandacuposcentro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndemandacuposcentroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndemandacuposcentroMouseExited(evt);
            }
        });
        btndemandacuposcentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndemandacuposcentroActionPerformed(evt);
            }
        });

        btnreporteconsumomedicamentos.setBackground(new java.awt.Color(247, 247, 247));
        btnreporteconsumomedicamentos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnreporteconsumomedicamentos.setText("Reporte de Consumo de Medicamentos");
        btnreporteconsumomedicamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnreporteconsumomedicamentosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnreporteconsumomedicamentosMouseExited(evt);
            }
        });
        btnreporteconsumomedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreporteconsumomedicamentosActionPerformed(evt);
            }
        });

        btnreporteconsultascanceladas.setBackground(new java.awt.Color(247, 247, 247));
        btnreporteconsultascanceladas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnreporteconsultascanceladas.setText("Reporte de Consultas Canceladas");
        btnreporteconsultascanceladas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnreporteconsultascanceladasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnreporteconsultascanceladasMouseExited(evt);
            }
        });
        btnreporteconsultascanceladas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreporteconsultascanceladasActionPerformed(evt);
            }
        });

        btnreimprimir.setBackground(new java.awt.Color(247, 247, 247));
        btnreimprimir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnreimprimir.setText("Reimprimir Consulta Atendida");
        btnreimprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnreimprimirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnreimprimirMouseExited(evt);
            }
        });
        btnreimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreimprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pprincipalLayout = new javax.swing.GroupLayout(pprincipal);
        pprincipal.setLayout(pprincipalLayout);
        pprincipalLayout.setHorizontalGroup(
            pprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pprincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pprincipalLayout.createSequentialGroup()
                            .addGroup(pprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnreporteconsultaespecialidades, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btndemandacuposcentro, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnreporteconsultascanceladas, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnreimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 11, Short.MAX_VALUE))
                        .addGroup(pprincipalLayout.createSequentialGroup()
                            .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42)))
                    .addGroup(pprincipalLayout.createSequentialGroup()
                        .addComponent(btnreporteconsumomedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pprincipalLayout.setVerticalGroup(
            pprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pprincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnregresar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnreporteconsultaespecialidades, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndemandacuposcentro, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnreporteconsumomedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnreporteconsultascanceladas, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnreimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(pprincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 300, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void psalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psalirMouseEntered
        // TODO add your handling code here:
        psalir.setBackground(Color.red);
    }//GEN-LAST:event_psalirMouseEntered

    private void psalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psalirMouseExited
        // TODO add your handling code here:
        psalir.setBackground(new Color(133,156,206));
    }//GEN-LAST:event_psalirMouseExited

    private void psalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psalirMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_psalirMouseClicked

    private void btnregresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnregresarActionPerformed

    private void btnreporteconsultaespecialidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporteconsultaespecialidadesActionPerformed
        // TODO add your handling code here:
        frmReporteEspecialidades abrir = new frmReporteEspecialidades();
        abrir.setVisible(true);
    }//GEN-LAST:event_btnreporteconsultaespecialidadesActionPerformed

    private void btndemandacuposcentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndemandacuposcentroActionPerformed
        // TODO add your handling code here:
        frmRDemandaCupos abrir = new frmRDemandaCupos();
        abrir.setVisible(true);
    }//GEN-LAST:event_btndemandacuposcentroActionPerformed

    private void btnreporteconsumomedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporteconsumomedicamentosActionPerformed
        // TODO add your handling code here:
        frmReporteConsumoMedicamentos abrir = new frmReporteConsumoMedicamentos();
        abrir.setVisible(true);
    }//GEN-LAST:event_btnreporteconsumomedicamentosActionPerformed

    private void btnreporteconsultascanceladasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreporteconsultascanceladasActionPerformed
        // TODO add your handling code here:
        frmRConsultasCanceladas abrir = new frmRConsultasCanceladas();
        abrir.setVisible(true);
    }//GEN-LAST:event_btnreporteconsultascanceladasActionPerformed

    private void btnreimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreimprimirActionPerformed
        // TODO add your handling code here:
        frmRImprimirConsulta abrir = new frmRImprimirConsulta();
        abrir.setVisible(true);
    }//GEN-LAST:event_btnreimprimirActionPerformed

    private void btnreporteconsultaespecialidadesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreporteconsultaespecialidadesMouseEntered
        // TODO add your handling code here:
        btnreporteconsultaespecialidades.setBackground(new Color(133,156,206));
    }//GEN-LAST:event_btnreporteconsultaespecialidadesMouseEntered

    private void btndemandacuposcentroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndemandacuposcentroMouseEntered
        // TODO add your handling code here:
        btndemandacuposcentro.setBackground(new Color(133,156,206));
    }//GEN-LAST:event_btndemandacuposcentroMouseEntered

    private void btnreporteconsumomedicamentosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreporteconsumomedicamentosMouseEntered
        // TODO add your handling code here:
        btnreporteconsumomedicamentos.setBackground(new Color(133,156,206));
    }//GEN-LAST:event_btnreporteconsumomedicamentosMouseEntered

    private void btnreporteconsultascanceladasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreporteconsultascanceladasMouseEntered
        // TODO add your handling code here:
        btnreporteconsultascanceladas.setBackground(new Color(133,156,206));
    }//GEN-LAST:event_btnreporteconsultascanceladasMouseEntered

    private void btnreimprimirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreimprimirMouseEntered
        // TODO add your handling code here:
        btnreimprimir.setBackground(new Color(133,156,206));
    }//GEN-LAST:event_btnreimprimirMouseEntered

    private void btnreporteconsultaespecialidadesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreporteconsultaespecialidadesMouseExited
        // TODO add your handling code here:
        btnreporteconsultaespecialidades.setBackground(new Color(247,247,247));
    }//GEN-LAST:event_btnreporteconsultaespecialidadesMouseExited

    private void btndemandacuposcentroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndemandacuposcentroMouseExited
        // TODO add your handling code here:
        btndemandacuposcentro.setBackground(new Color(247,247,247));
    }//GEN-LAST:event_btndemandacuposcentroMouseExited

    private void btnreporteconsumomedicamentosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreporteconsumomedicamentosMouseExited
        // TODO add your handling code here:
        btnreporteconsumomedicamentos.setBackground(new Color(247,247,247));
    }//GEN-LAST:event_btnreporteconsumomedicamentosMouseExited

    private void btnreporteconsultascanceladasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreporteconsultascanceladasMouseExited
        // TODO add your handling code here:
        btnreporteconsultascanceladas.setBackground(new Color(247,247,247));
    }//GEN-LAST:event_btnreporteconsultascanceladasMouseExited

    private void btnreimprimirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreimprimirMouseExited
        // TODO add your handling code here:
        btnreimprimir.setBackground(new Color(247,247,247));
    }//GEN-LAST:event_btnreimprimirMouseExited

    private void btnregresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregresarMouseEntered
        // TODO add your handling code here:
        btnregresar.setBackground(new Color(133,156,206));
    }//GEN-LAST:event_btnregresarMouseEntered

    private void btnregresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregresarMouseExited
        // TODO add your handling code here:
        btnregresar.setBackground(new Color(247,247,247));
    }//GEN-LAST:event_btnregresarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndemandacuposcentro;
    private javax.swing.JButton btnregresar;
    private javax.swing.JButton btnreimprimir;
    private javax.swing.JButton btnreporteconsultaespecialidades;
    private javax.swing.JButton btnreporteconsultascanceladas;
    private javax.swing.JButton btnreporteconsumomedicamentos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pprincipal;
    private javax.swing.JPanel psalir;
    // End of variables declaration//GEN-END:variables
}
